export enum RideStatus {
  SEARCHING_DRIVER = 'SEARCHING_DRIVER',
  DRIVER_FOUND = 'DRIVER_FOUND',
  DRIVER_ARRIVED = 'DRIVER_ARRIVED',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  ONGOING = 'ONGOING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  FARE_NEGOTIATION = 'FARE_NEGOTIATION',
  ACCEPTED = 'ACCEPTED',
  STARTED = 'STARTED',
  PENDING = 'PENDING',
}
